language: node_js

node_js:
  - "node"
  - "6"
  - "5"
sudo: required

before_script:
  - npm install -g cordova
  - npm install -g ionic

install:
  - npm install

script:
  - npm cordova run ionic:build --prod
